### ISSUE TITLE
Copy project

### ISSUE THREAD

**Issue by UN7RX** [qrp73/ali_trx#1]
Your project is 100% copied [from here](http://www.cqham.ru/forum/showthread.php?35923-DDC-DUC-%F2%F0%E0%ED%F1%E8%E2%E5%F0-%F1-%E8%ED%F2%E5%F0%F4%E5%E9%F1%EE%EC-Ethernet-%E8%E7-%EC%EE%E4%F3%EB%E5%E9-%F1-%C0%EB%E8). Why didn't you name the author?

**Comment by qrp73** [comment]
No, you're wrong, my project is a clone of [Hermes-Lite project]([Hermes-Lite](https://github.com/softerhardware/Hermes-Lite)). 

The original Hermes-lite project fork which I was used for a clone is a GNU licensed project which author is [Steve Haynal](https://github.com/softerhardware). His original copyright with the author name is included in my clone.


By the way, this Hermes-lite clone is actually very outdated and has some issues, because I made it when I was a novice in FPGA design and didn't know about many things, such as metastability and clock synchronization. There was some updates and fixes, but I just abandoned that project, because it has a lot of issues. After that I also worked on Hermes-lite-2 clone and rewrote all DSP code, but later I was needed for a higher bandwidth and just decided to abandon that project, because it uses HPSDR protocol which has too many overhead.

Currently I'm working on a complete new gateware for DDC receiver which is designed from scratch. I replaced 100M PHY with 1G GMII PHY controller. And now I'm using ethernet UDP stack written by [Alex Forencich](https://github.com/alexforencich), thanks to Steve Haynal for his recommendation. It use 1G ethernet speed. 

Also there is a complete new DSP code, I'm using a new NCO with better spurious performance, also I implemented a new filters calculated in MATLAB with much better dynamic range. So the total performance now is better, my new DDC has less spurs, less signal processing noise.

Also I'm working on a PC software for my DDC which utilize GPU acceleration, Currently it has Direct2D renderer, but I'm planning to move it to OpenGL and to implement fosphor feature, like [this one](https://www.youtube.com/watch?v=mjD-l3GAghU).

**Comment by qrp73** [comment]
If you're interested, here is response of the FIR filter used in this hermes-lite clone (it also used in other OpenHPSDR open source projects) and for comparison response of my new FIR. In addition to that dynamic range improvements, I also using a new NCO and CIC implementation to eliminate some spurs.

The blue is a CIC filter response, the green is a FIR filter response and the red is a combined CIC+FIR response.

![original-cic-firX2R2](https://user-images.githubusercontent.com/46676744/175667291-f9978718-9574-42de-90a8-e62e143cf6c2.png)

![my-cic-fir](https://user-images.githubusercontent.com/46676744/175667315-0c5de151-9965-4850-8fd1-9ac83734cf44.png)
